import {
  AlarmClock,
  ArrowDownUp,
  ArrowLeftRight,
  Beaker,
  Briefcase,
  Blend,
  BotOff,
  Baseline,
  Binary,
  BookOpen,
  Braces,
  Cake,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  CalendarRange,
  CaseSensitive,
  Clock,
  Clock4,
  Columns3,
  Code,
  CodeXml,
  Combine,
  Crop,
  Database,
  Dices,
  Dice5,
  Eraser,
  FileCode,
  FileImage,
  FileInput,
  FileJson,
  FileOutput,
  FileSearch,
  FileSignature,
  FileSpreadsheet,
  Fingerprint,
  FileText,
  Contrast,
  Gauge,
  GitCompare,
  Globe,
  HardDrive,
  Hourglass,
  Hash,
  ImageDown,
  ImageMinus,
  Images,
  KeyRound,
  KeySquare,
  Languages,
  Layers,
  Link,
  Link2,
  ListChecks,
  ListOrdered,
  ListTodo,
  Lock,
  Map,
  MousePointerClick,
  LayoutTemplate,
  Mail,
  Minimize2,
  NotebookPen,
  Paintbrush,
  Palette,
  Pipette,
  Percent,
  Pilcrow,
  Regex,
  Replace,
  QrCode,
  Receipt,
  Ruler,
  Scale,
  ScanBarcode,
  ScanLine,
  Scaling,
  Scissors,
  Search,
  ShieldCheck,
  Shuffle,
  Share2,
  Sparkles,
  SpellCheck,
  Square,
  SquareDashed,
  SwatchBook,
  Table,
  Tags,
  Target,
  Thermometer,
  Ticket,
  TextQuote,
  Timer,
  TimerReset,
  TrendingUpDown,
  Type,
  TrendingUp,
  UserRound,
  Weight,
  Wallet,
  Wrench,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";
import type { ToolCategory } from "@/lib/tool-types";

const ICONS: Record<string, LucideIcon> = {
  receipt: Receipt,
  "file-signature": FileSignature,
  "trending-up": TrendingUp,
  percent: Percent,
  wallet: Wallet,
  "arrow-left-right": ArrowLeftRight,
  "file-text": FileText,
  combine: Combine,
  scissors: Scissors,
  "image-down": ImageDown,
  "image-minus": ImageMinus,
  scaling: Scaling,
  "layout-template": LayoutTemplate,
  "qr-code": QrCode,
  "key-round": KeyRound,
  "scan-barcode": ScanBarcode,
  sparkles: Sparkles,
  mail: Mail,

  // Text tools
  type: Type,
  hash: Hash,
  "case-sensitive": CaseSensitive,
  pilcrow: Pilcrow,
  "text-quote": TextQuote,
  "spell-check": SpellCheck,
  "book-open": BookOpen,
  timer: Timer,
  eraser: Eraser,
  "arrow-down-up": ArrowDownUp,
  replace: Replace,
  shuffle: Shuffle,
  "list-ordered": ListOrdered,
  baseline: Baseline,
  link: Link,
  search: Search,
  "git-compare": GitCompare,

  // Developer tools
  braces: Braces,
  code: Code,
  "code-xml": CodeXml,
  "file-code": FileCode,
  "file-json": FileJson,
  database: Database,
  binary: Binary,
  fingerprint: Fingerprint,
  clock: Clock,
  "calendar-clock": CalendarClock,
  regex: Regex,
  "minimize-2": Minimize2,
  dices: Dices,
  globe: Globe,
  "shield-check": ShieldCheck,
  paintbrush: Paintbrush,

  // Unit converters
  ruler: Ruler,
  weight: Weight,
  thermometer: Thermometer,
  square: Square,
  beaker: Beaker,
  gauge: Gauge,
  "hard-drive": HardDrive,
  hourglass: Hourglass,

  // Colour and design
  palette: Palette,
  pipette: Pipette,
  swatchbook: SwatchBook,
  blend: Blend,
  contrast: Contrast,
  "square-dashed": SquareDashed,
  "mouse-pointer-click": MousePointerClick,
  layers: Layers,

  // SEO and web
  tags: Tags,

  // Files, images and random
  table: Table,
  "file-spreadsheet": FileSpreadsheet,
  "file-search": FileSearch,
  "file-input": FileInput,
  "file-output": FileOutput,
  crop: Crop,
  "file-image": FileImage,
  images: Images,
  "scan-line": ScanLine,
  lock: Lock,
  dice5: Dice5,
  ticket: Ticket,
  "user-round": UserRound,
  "key-square": KeySquare,

  // Date, time and productivity
  "calendar-days": CalendarDays,
  cake: Cake,
  briefcase: Briefcase,
  "calendar-plus": CalendarPlus,
  "clock-4": Clock4,
  "timer-reset": TimerReset,
  "alarm-clock": AlarmClock,
  "list-todo": ListTodo,
  "notebook-pen": NotebookPen,
  "list-checks": ListChecks,
  "calendar-check": CalendarCheck,
  "calendar-range": CalendarRange,
  columns3: Columns3,
  target: Target,
  scale: Scale,
  share2: Share2,
  "bot-off": BotOff,
  map: Map,
  "link-2": Link2,
  "trending-up-down": TrendingUpDown,
  languages: Languages,
  braces2: Braces,
};

/** Category tints keep the grid readable without relying on colour alone. */
const CATEGORY_TINT: Record<ToolCategory, string> = {
  calculators: "bg-sky-50 text-sky-700 dark:bg-sky-950/60 dark:text-sky-300",
  finance: "bg-navy-50 text-navy-700 dark:bg-navy-900/70 dark:text-navy-200",
  business: "bg-navy-50 text-navy-700 dark:bg-navy-900/70 dark:text-navy-200",
  datetime: "bg-rose-50 text-rose-700 dark:bg-rose-950/60 dark:text-rose-300",
  text: "bg-emerald-50 text-emerald-700 dark:bg-emerald-950/60 dark:text-emerald-300",
  units: "bg-cyan-50 text-cyan-700 dark:bg-cyan-950/60 dark:text-cyan-300",
  files: "bg-teal-50 text-teal-700 dark:bg-teal-900/50 dark:text-teal-200",
  images: "bg-amber-50 text-amber-700 dark:bg-amber-950/60 dark:text-amber-300",
  generators: "bg-violet-50 text-violet-700 dark:bg-violet-950/60 dark:text-violet-300",
  developer: "bg-slate-100 text-slate-700 dark:bg-slate-800/70 dark:text-slate-300",
  design: "bg-fuchsia-50 text-fuchsia-700 dark:bg-fuchsia-950/60 dark:text-fuchsia-300",
  seo: "bg-lime-50 text-lime-700 dark:bg-lime-950/60 dark:text-lime-300",
  productivity: "bg-indigo-50 text-indigo-700 dark:bg-indigo-950/60 dark:text-indigo-300",
};

export function ToolIcon({
  icon,
  category,
  className,
  size = "md",
}: {
  icon: string;
  category: ToolCategory;
  className?: string;
  size?: "sm" | "md" | "lg";
}) {
  const Icon = ICONS[icon] ?? Wrench;
  const box = { sm: "size-8 rounded-lg", md: "size-10 rounded-xl", lg: "size-12 rounded-xl" }[size];
  const glyph = { sm: "size-4", md: "size-5", lg: "size-6" }[size];

  return (
    <span
      className={cn("inline-flex items-center justify-center", box, CATEGORY_TINT[category], className)}
      aria-hidden="true"
    >
      <Icon className={glyph} strokeWidth={1.9} />
    </span>
  );
}
